version: "3.9"

services:
  service1:
    image: letsgetrusty/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it

  proxy:
    image: letsgetrusty/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      POSTMARK_AUTH_TOKEN: ${POSTMARK_AUTH_TOKEN}
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it
